### ISSUE TITLE
Unknown props while porting react-bootstrap component

### ISSUE THREAD

**Issue by nlhkh** [payalabs/scalajs-react-bridge#16] opened 2016-07-23 19:16 UTC
I ran into this error when I created the `Navbar`, `Nav`, `NavbarHeader`, `NavbarBrand`. It broke the javascript and nothing is rendered.

Do you have any clue how I can fix this?

```javascript
client-jsdeps.js:22536Warning: Unknown props `bsClass`, `bsStyle`, `expanded`, `onToggle` on <nav> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by Router)
    in div (created by Router)
    in div (created by Router)
    in Routerwarning @ client-jsdeps.js:22536warnUnknownProperties @ client-jsdeps.js:10112handleElement @ client-jsdeps.js:10123onBeforeMountComponent @ client-jsdeps.js:10128(anonymous function) @ client-jsdeps.js:10165emitEvent @ client-jsdeps.js:10162onBeforeMountComponent @ client-jsdeps.js:10409mountComponent @ client-jsdeps.js:14463performInitialMount @ client-jsdeps.js:6390mountComponent @ client-jsdeps.js:6264mountComponent @ client-jsdeps.js:14467performInitialMount @ client-jsdeps.js:6390mountComponent @ client-jsdeps.js:6264mountComponent @ client-jsdeps.js:14467mountChildren @ client-jsdeps.js:12817_createInitialChildren @ client-jsdeps.js:7780mountComponent @ client-jsdeps.js:7605mountComponent @ client-jsdeps.js:14467mountChildren @ client-jsdeps.js:12817_createInitialChildren @ client-jsdeps.js:7780mountComponent @ client-jsdeps.js:7605mountComponent @ client-jsdeps.js:14467performInitialMount @ client-jsdeps.js:6390mountComponent @ client-jsdeps.js:6264mountComponent @ client-jsdeps.js:14467performInitialMount @ client-jsdeps.js:6390mountComponent @ client-jsdeps.js:6264mountComponent @ client-jsdeps.js:14467mountComponentIntoNode @ client-jsdeps.js:12180perform @ client-jsdeps.js:18733batchedMountComponentIntoNode @ client-jsdeps.js:12201perform @ client-jsdeps.js:18733batchedUpdates @ client-jsdeps.js:10503batchedUpdates @ client-jsdeps.js:16382_renderNewRootComponent @ client-jsdeps.js:12360_renderSubtreeIntoContainer @ client-jsdeps.js:12446render @ client-jsdeps.js:12467$c_Ladmin_Admin$.main__V @ Admin.scala:16$c_Ladmin_Admin$.$$js$exported$meth$main__O @ Admin.scala:14$c_Ladmin_Admin$.main @ Admin.scala:14(anonymous function) @ client-launcher.js:2
client-jsdeps.js:22536 Warning: Unknown props `fluid`, `componentClass` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Grid)
    in Grid (created by Navbar)
    in nav (created by Navbar)
    in Navbar (created by Uncontrolled(Navbar))
    in Uncontrolled(Navbar) (created by Router)
    in div (created by Router)
    in div (created by Router)
    in Router
```

**Comment by ramnivas** [comment] 2016-07-29 18:00
How does your bridge component looks like?

**Comment by nlhkh** [comment] 2016-08-01 17:29
I have my Navbar like this
```scala
case class Navbar(id: js.UndefOr[String] = js.undefined,
                  className: js.UndefOr[String] = js.undefined,
                  ref: js.UndefOr[String] = js.undefined,
                  key: js.UndefOr[Any] = js.undefined) extends ReactBootstrap
```

And then I tried the followings
```scala
case class NavbarBrand(id: js.UndefOr[String] = js.undefined,
                       className: js.UndefOr[String] = js.undefined,
                       ref: js.UndefOr[String] = js.undefined,
                       key: js.UndefOr[Any] = js.undefined) extends ReactBootstrap

// ———— Or ———— //

case class Navbar(id: js.UndefOr[String] = js.undefined,
                  className: js.UndefOr[String] = js.undefined,
                  ref: js.UndefOr[String] = js.undefined,
                  key: js.UndefOr[Any] = js.undefined) extends ReactBootstrap

object Navbar {
    case class Brand(id: js.UndefOr[String] = js.undefined,
                       className: js.UndefOr[String] = js.undefined,
                       ref: js.UndefOr[String] = js.undefined,
                       key: js.UndefOr[Any] = js.undefined) extends ReactBootstrap
}
```

**Comment by ramnivas** [comment] 2016-08-01 17:37
And how do you instantiate these components?

**Comment by ramnivas** [comment] 2016-08-01 17:38
And how does your `ReactBootstrap` look like?

**Comment by nlhkh** [comment] 2016-08-01 17:45
The `ReactBootstrap` is
```scala
@ComponentNamespace("ReactBootstrap")
abstract class ReactBootstrap extends ReactBridgeComponent
```
which I stole from your example.

I no longer have the code, but I remember instantiating them like this
```scala
Navbar()(
  NavbarBrand()(...)
)
```

**Comment by ramnivas** [comment] 2016-08-01 18:39
It is difficult to figure out without that code what might be going on. I don't see where `bsClass` etc props are passed. I will close this issue for now. If you find that code (ideally as a repo so that I can reproduce), we can reopen this.

**Closed by ramnivas** 2016-08-01 18:39 UTC

**Comment by chandu0101** [comment] 2016-08-02 10:02
@nlhkh  what version of react-boostrap you using .. ? 

https://github.com/react-bootstrap/react-bootstrap/issues/1994

**Comment by nlhkh** [comment] 2016-08-02 10:23
v0.30.1

**Comment by chandu0101** [comment] 2016-08-02 10:55
ok, try 0.30.0 . anyway its react-bootstrap and react issue :)

**Comment by nlhkh** [comment] 2016-08-02 16:28
I actually reattempt at this, and here is my components:

```scala
object Navbar {

  case class NavbarHeader(id: js.UndefOr[String] = js.undefined,
                          className: js.UndefOr[String] = js.undefined,
                          ref: js.UndefOr[String] = js.undefined,
                          key: js.UndefOr[Any] = js.undefined,
                          bsClass: js.UndefOr[String] = "navbar") extends ReactBootstrap

  case class NavbarBrand(id: js.UndefOr[String] = js.undefined,
                         className: js.UndefOr[String] = js.undefined,
                         ref: js.UndefOr[String] = js.undefined,
                         key: js.UndefOr[Any] = js.undefined,
                         bsClass: js.UndefOr[String] = "navbar") extends ReactBootstrap

}
```

The `NavbarBranch` works, but `NavbarHeader` does not work with error
```
client-jsdeps.js:22536Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Router`.warning @ client-jsdeps.js:22536createElement @ client-jsdeps.js:11113$c_Ladmin_components_layout_Layout$.apply__Ljapgolly_scalajs_react_extra_router_RouterCtl__Ljapgolly_scalajs_react_extra_router_Resolution__Ljapgolly_scalajs_react_vdom_ReactTagOf @ ReactBridgeComponent.scala:37(anonymous function) @ AdminRouter.scala:23$c_sjsr_AnonFunction2.apply__O__O__O @ AnonFunctions.scala:20$c_Ljapgolly_scalajs_react_extra_router_RouterLogic.render__Ljapgolly_scalajs_react_extra_router_Resolution__Ljapgolly_scalajs_react_ReactElement @ Router.scala:142(anonymous function) @ Router.scala:20$c_sjsr_AnonFunction1.apply__O__O @ AnonFunctions.scala:15(anonymous function) @ ReactComponentB.scala:178$c_sjsr_AnonFunction1.apply__O__O @ AnonFunctions.scala:15Router_render @ ReactComponentB.scala:395_renderValidatedComponentWithoutOwnerOrContext @ client-jsdeps.js:6808_renderValidatedComponent @ client-jsdeps.js:6834performInitialMount @ client-jsdeps.js:6376mountComponent @ client-jsdeps.js:6264mountComponent @ client-jsdeps.js:14467performInitialMount @ client-jsdeps.js:6390mountComponent @ client-jsdeps.js:6264mountComponent @ client-jsdeps.js:14467mountComponentIntoNode @ client-jsdeps.js:12180perform @ client-jsdeps.js:18733batchedMountComponentIntoNode @ client-jsdeps.js:12201perform @ client-jsdeps.js:18733batchedUpdates @ client-jsdeps.js:10503batchedUpdates @ client-jsdeps.js:16382_renderNewRootComponent @ client-jsdeps.js:12360_renderSubtreeIntoContainer @ client-jsdeps.js:12446render @ client-jsdeps.js:12467$c_Ladmin_Admin$.main__V @ Admin.scala:16$c_Ladmin_Admin$.$$js$exported$meth$main__O @ Admin.scala:14$c_Ladmin_Admin$.main @ Admin.scala:14(anonymous function) @ client-launcher.js:2
client-jsdeps.js:22144 Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Router`.
```

This is error is very likely that the bridge cannot find the `NavbarHeader`. I tried changing the class name of other components, and got the same error. However, I have no idea why it cannot find `NavbarHeader` when that component is visible in JS.
